permissions:
  contents: write
  actions: read

name: Sync Folder to GitHub Pages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync-folder]

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
      # Checkout target
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Clone source
      - name: Clone Source Repository
        run: |
          git clone https://github.com/SWEvenTeam17/documentazione.git source-repo

      # Copy folders from source
      - name: Copy Folders
        run: |
          mkdir -p docs
          cp -r source-repo/* docs/

      # Configure git for push
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Commit and push changes to target
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Sync folder from source"
          git push origin main

      # Cleanup cloned source
      - name: Cleanup
        run: |
          rm -rf source-repo
